name: Auto Deploy to HostDare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/sukjmart
            git pull origin main
            npm install
            pm2 delete mygame || true
            pm2 start server.js --name "mygame"
            pm2 save
