name: Auto Deploy to HostDare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/sukjmart
            git fetch origin main
            git reset --hard origin/main
            npm install
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
            pm2 save
